const generateAgreementText = (assetTitle, communityName, licenseType) => {
    const duration = '1 year fixed';
    return `LICENSE AGREEMENT

This Agreement is made regarding the cultural asset titled "${assetTitle}".
Community of Origin: ${communityName}
License Type: ${licenseType}
Duration: ${duration}

Terms and Conditions:
1. The licensee is granted a non-exclusive right to use the asset in accordance with the ${licenseType} guidelines.
2. Non-Transfer Clause: This license is strictly non-transferable and cannot be sublicensed, sold, or assigned to any third party.
3. The licensee must attribute the ${communityName} community in all uses of this asset.
4. This agreement is valid for a period of ${duration} from the date of approval.

Approved and generated by DHAROHAR System.`;
};

module.exports = { generateAgreementText };
